In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [4]:
print(q_table)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [7]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [8]:
rewards_all_episodes = []

In [9]:
# Q-learning algorithm
for episode in range(num_episodes):
  # initialize new episode params
  state = env.reset()
  
  done = False
  rewards_current_episode = 0
  
  for step in range(max_steps_per_episode): 
    # Exploration-exploitation trade-off
    exploration_rate_threshold = random.uniform(0, 1)
    if exploration_rate_threshold > exploration_rate:
      action = np.argmax(q_table[state,:]) 
    else:
      action = env.action_space.sample()
      
    # Take new action
    new_state, reward, done, info = env.step(action)
    
    # Update Q-table
    q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
                              learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
    # Set new state
    state = new_state
        
    # Add new reward        
    rewards_current_episode += reward 
    
    if done == True: 
      break
    
  # Exploration rate decay   
  exploration_rate = min_exploration_rate + \
                    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

  # Add current episode reward to total rewards list
  rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
  print(count, ": ", str(sum(r/1000)))
  count += 1000
    
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.158
2000 :  0.464
3000 :  0.578
4000 :  0.615
5000 :  0.652
6000 :  0.658
7000 :  0.658
8000 :  0.696
9000 :  0.689
10000 :  0.665


********Q-table********

[[ 0.50913116  0.49309049  0.50038797  0.49789538]
 [ 0.25381369  0.23476883  0.11594088  0.4492495 ]
 [ 0.35417157  0.12799526  0.18694151  0.24862482]
 [ 0.07278711  0.          0.          0.        ]
 [ 0.52003304  0.30835641  0.41306503  0.38243378]
 [ 0.          0.          0.          0.        ]
 [ 0.2520174   0.109071    0.19628515  0.08262408]
 [ 0.          0.          0.          0.        ]
 [ 0.36999509  0.48828566  0.39870365  0.55117909]
 [ 0.46316305  0.6212212   0.42643342  0.38460274]
 [ 0.56172021  0.38883439  0.36574705  0.20534314]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.37100955  0.43696735  0.72266554  0.52592647]
 [ 0.69199773  0.84937907  0.77235564  0.73267991]
 [ 0.        